---
- name: add admin user
  user:
    name: "{{ sudoer }}"
    shell: /bin/bash

- name: configure authorized keys for admin user
  authorized_key:
    user: "{{ sudoer }}"
    key: "{{ lookup('file', item) }}"
  with_items: "{{ sudoer_public_keys }}"

- name: create sudoers.d directory
  file:
    path: /etc/sudoers.d
    owner: root
    group: root
    mode: 0755
    state: directory

- name: set includedir in sudoers
  lineinfile:
    dest: /etc/sudoers
    line: "#includedir /etc/sudoers.d"
    state: present
    validate: "/usr/sbin/visudo -cf %s"

- name: create sudoer file for admin
  template:
    src: sudoers.d.j2
    dest: "/etc/sudoers.d/{{ sudoer }}"
    mode: 0440
    owner: root
    group: root
    validate: "/usr/sbin/visudo -cf %s"